### ISSUE TITLE
Problem with installing and running Mapzen demo.

### ISSUE THREAD

**Issue by stepanmazokha** [mapzen/open#440]
I download Mapzen Open to my desktop, add local.properties file with sdk.dir=/Applications/sdk for path of android sdk and here's what I get after running `$ ./scripts/install-dependencies.sh` command:

>FAILURE: Build failed with an exception.

>* What went wrong:
>A problem occurred configuring project ':vtm-android'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an >ANDROID_HOME environment variable.

>* Try:
>Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log >output.

>BUILD FAILED

P.S. path /Applications/sdk is valid.

**Comment by ecgreb** [comment]
You need to set the environment variable `ANDROID_HOME` so the Android Maven Plugin can find your Android SDK. This is different than setting `sdk.dir` in `local.properties`.

Fore more information see https://simpligility.github.io/android-maven-plugin/.

**Comment by mjcunningham** [comment]
Hi @stepanmazokha . We are actually not going to be supporting the Open app anymore. We have been hard at work on a new app over [here](https://github.com/mapzen/eraser-map) and we'd love for you to sing up to be a [beta tester](https://www.erasermap.com/).
