### ISSUE TITLE
Installing dependencies fails

### ISSUE THREAD

**Issue by josephkandi** [mapzen/open#441]
When i run `mvn clean install`, i get the following error
[ERROR] Failed to execute goal on project open: Could not resolve dependencies for project com.mapzen.android:open:apk:1.2.2-SNAPSHOT: Failure to find com.android.support:support-v4:jar:21.0.3 in https://mint.splunk.com/maven/ was cached in the local repository, resolution will not be reattempted until the update interval of Splunk MINT repo has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException:

My environment variables : 
`Josephs-MacBook-Pro:~ joseph$ echo $M2_HOME $JAVA_HOME $ANDROID_HOME 
/usr/local/Cellar/maven/3.3.3/libexec /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home /Users/joseph/Library/Android/sdk`

Also got this error :
`Downloading support_r21.0.3.zip
scripts/dependency/install-support-jar_app.sh: line 13: wget: command not found
unzip:  cannot find or open support_r21.0.3.zip, support_r21.0.3.zip.zip or support_r21.0.3.zip.ZIP.` 

I have the unzip command in my PATH, not sure if its the unzip command not found or the support library

**Comment by ecgreb** [comment]
It looks like `wget` is not on your PATH and it was unable to download the artifact. So when it went to `unzip` there was nothing there.

**Comment by josephkandi** [comment]
Thanks, worked like a charm
