### ISSUE TITLE
Android Studio Build

### ISSUE THREAD

**Issue by josephkandi** [mapzen/open#442]
Is it possible to have a build using gradle with Android Studio seeing that the ADT is being phased out?

**Comment by ecgreb** [comment]
Open currently uses Maven (not ADT) for the build system. There are no immediate plans to migrate this project to Gradle. Maven is fully compatible with IntelliJ IDEA (which Android Studio is based on).

**Comment by josephkandi** [comment]
I did build the project from the terminal successfully, but i do get a lot of errors when i import into Android Studio or IntelliJ. I did add Maven plugin to Android Studio but still the project have a lot of errors. It can not find a lot of classes. So which IDE should i use after i have built the project from the terminal without having issues resolving libraries and classes?

**Comment by ecgreb** [comment]
I have not tried the Maven plugin for Android Studio. I stick to IntelliJ for all our Maven based projects. Which dependencies are unable to be resolved?

**Comment by josephkandi** [comment]
Works fine in IntelliJ, problem was i created the project from existing sources instead of doing an import from  a Maven project.

**Comment by ecgreb** [comment]
Glad to hear you got it sorted out.
