### ISSUE TITLE
rivers not drawing properly

### ISSUE THREAD

**Issue by adriangradinar** [mapzen/open#444]
I've spotted an issue with the drawing of the water elements. Any ideas?
![screenshot_2015-10-02-17-41-56](https://cloud.githubusercontent.com/assets/5746928/10252130/5a19ceea-692d-11e5-9142-7f527a0591c9.png)

**Comment by ecgreb** [comment]
@hjanetzek any guess why this might be occurring? I am seeing the same thing in the version currently in the play store.

![image](https://cloud.githubusercontent.com/assets/464123/10256534/ea64a87a-691f-11e5-8a3c-56acaaf1dda0.png)

**Comment by hjanetzek** [comment]
@ecgreb, yes, some line features are matched by draw rules for polygons now since line features got additional tags for which landuse type they cross. Adding some more closed="yes" to rules that should only handle polygon will fix this.

**Comment by adriangradinar** [comment]
It worked! Thank you :)
