### ISSUE TITLE
Footpath drawing

### ISSUE THREAD

**Issue by adriangradinar** [mapzen/open#446]
Hi guys,
Been trying to display a footpath using a dash-array and I don't know why every time I use dasharrays they are rendered as solid lines not as dots. If I use the stipple, it's all good, but I'd like to emphasise walking routes so a dotted line is more appropriate.
The following code works perfect for railways and similar requirements

line stroke="#333333" width="0" cap="round" fade="12" fix="true" stipple="20" stipple-width="1.2" stipple-stroke="#00e6e6e6"

How can I display a dotted line?

Thanks!

**Comment by hjanetzek** [comment]
Open uses the VTM renderer which does not have dotted line patterns. Also the dashed-array syntax is not implemented (it's a relict in the Open stylesheet from the old mapsforge theme) 

You can submit a feature request there, but the development has quite stalled:
 https://github.com/opensciencemap/vtm

**Comment by adriangradinar** [comment]
Okies, thx for this. Anyway I could display dots without using a dash-array? Do line features work with images/patterns (similar to areas)?

Thanks!

**Comment by mjcunningham** [comment]
@nvkelso @bcamper

**Comment by mjcunningham** [comment]
Hi @adriangradinar. We are actually not going to be supporting the Open app anymore. We have been hard at work on a new app over [here](https://github.com/mapzen/eraser-map) and we'd love for you to sing up to be a [beta tester](https://www.erasermap.com/).
