### ISSUE TITLE
Bring it to F-Droid?

### ISSUE THREAD

**Issue by IzzySoft** [mapzen/open#450]
Being "Really, really open" (quoted from your app's Playstore description), I wonder why *Open* cannot be found at F-Droid? Their wiki writes something about build issues (see: [Open by Mapzen](https://f-droid.org/wiki/index.php?title=Open_by_Mapzen), linking to issue #356 – which is long closed).

Main reason I'm asking is the growing community of "Google resisters" using e.g. [microG](https://github.com/microg/) and having all GApps banned – completely going for open source (I have two devices running that way). Accessing playstore is hard for some, not an option for others. Are there any chances we'll see *Open* at F-Droid in the foreseeable future?

**Comment by ecgreb** [comment]
The main issue here is that the app requires OpenSteetMap login to enable optional features such as contributing GPX traces back to OSM.

We rely on a single private dependency to securely authenticate the user with OSM.

It is (or was) possible to build a version of the app without OSM integration. There was some work done to this end a while back.

https://github.com/mapzen/open/pull/364

We should revisit this if its not currently working and consider launching a version of the app in F-Droid that does not include OSM login.

**Comment by IzzySoft** [comment]
Sounds like a plan. Thanks for the feedback! I'll keep watching this issue for updates :innocent:

Btw: my [app listing](https://android.izzysoft.de/applists/category/named/travel_positioning_navigation) will pick up the F-Droid listing automatically when it finally happens :smiley_cat:

**Comment by zerebubuth** [comment]
@ecgreb, would it be possible to allow users to login using their own OSM account, or create one? The OAuth process is relatively simple; just a few HTTP calls and a WebView to open.

This might be a better idea than sharing an account between all the app's users, as sharing an account means that bad behaviour from any one user would result in problems for everyone using the account.

**Comment by msmollin** [comment]
@zerebubuth Open does use OAuth for users, and isn't lumping everyone under one account. The private repo @ecgreb is referring to contains Open's API OAuth keys that you get from registering your application for API access here - https://www.openstreetmap.org/user/username/oauth_clients/new

This is how we identify ourselves to users in the aforementioned webview, and define what level of access / types of access we need for the application.

**Comment by zerebubuth** [comment]
@msmollin great! Thanks for correcting my wrong assumption. :smile:

**Comment by mjcunningham** [comment]
Hi @IzzySoft . We are actually not going to be supporting the Open app anymore. We have been hard at work on a new app over [here](https://github.com/mapzen/eraser-map) and we'd love for you to sing up to be a [beta tester](https://www.erasermap.com/).

**Comment by IzzySoft** [comment]
Hi @mjcunningham and thanks for the feedback! I won't be a good beta tester due to lack of time. But if you wish to have the referenced app in an F-Droid repo, let me know (see [here](https://apt.izzysoft.de/ftp/repo/fdroid/) what I'm referencing). You already have the `.apk` files under `releases/`, which is perfect: as soon as there's a "release" (and not only "pre-release"), I could pick it up automatically, just need to add the URL to my configuration :)
